name: Audit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: latest
      - name: fcli definitions update
        run: fcli tool definitions update
      - name: fcli tool list
        run: fcli tool fcli list
      - name: fcli install
        run: fcli tool fcli install
      - name: fcli version dump
        run: fcli -V

