name: Audit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: latest
      - name: Run fcli from PATH
        run: fcli -V
