name: Audit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: latest
      - name: aviator admin login
        run: admin-config create --url ${{vars.AVIATOR_URL}} --tenant ${{vars.AVIATOR_TENANT}} --private-key ${{secrets.AVIATOR_KEY}}
      - name: aviator app list
        run: fcli aviator app list

