name: Audit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: latest

# To run SAST Aviator admin commands, you can run commands like this. "secrets.AVIATOR_KEY" must contain the RSA 4096 private key. It
# must in in PEM format, removed of all newlines, and prefixed by "string:". However, normally, you wouldn't use
# SAST Aviator admin access in the context of a build pipeline.
#      - name: aviator admin login
#        run: fcli aviator admin-config create --url ${{vars.AVIATOR_URL}} --tenant ${{vars.AVIATOR_TENANT}} --private-key "${{secrets.AVIATOR_KEY}}"
#      - name: aviator app list
#        run: fcli aviator app list


      - name: aviator session login
        run: fcli aviator session login --url ${{vars.AVIATOR_URL}} --token "${{secrets.AVIATOR_TOKEN}}"
      - name: SSC session login
        run: fcli ssc session login --url ${{vars.SSC_URL}} --token "${{secrets.SSC_TOKEN}}"
