name: Remediate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v2
        with:
          fcli: latest

      - name: SSC session login
        run: fcli ssc session login --url ${{vars.SSC_URL}} --token "${{secrets.SSC_TOKEN}}"

      - name: Apply remediations
        run: |
          ARTIFACT_ID=$(fcli ssc artifact ls --av "${{vars.APPLICATION_NAME}}:${{github.ref_name}}" --output json | 
            jq -r '
              [.[] | select(.originalFileName | startswith("aviator_"))] | 
              sort_by(.uploadDate) | 
              last | 
              .id
            ')
          echo "Latest aviator artifact ID: $ARTIFACT_ID"
          fcli aviator ssc apply-remediations --artifact-id $ARTIFACT_ID

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'auto-remediation by OpenText SAST Aviator'
          branch: aviator/remediate-${{ github.run_id }}
          delete-branch: true
          title: 'Remediation of security issues detected by OpenText SAST'
          body: |
            Remediation of security issues detected by OpenText SAST.
            This PR was automatically created by OpenText SAST Aviator.
            Please review carefully before merging.
