name: Scan-Audit-Remediate

on:
  workflow_dispatch:

jobs:
  scan_audit_remediate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run ScanCentral SAST and Aviator audit
        uses: fortify/github-action@v3
        env:
          FCLI_BOOTSTRAP_VERSION: ${{vars.FCLI_VERSION}}
          SSC_URL: ${{vars.SSC_URL}}
          SC_CLIENT_VERSION: ${{vars.SC_CLIENT_VERSION}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SC_SAST_TOKEN: ${{secrets.SC_SAST_CLIENT_AUTH_TOKEN}}
          # Including the run_id in the app version name. This doesn't make a lot of sense in production, but enables
          # us to run this demo many times.
          SSC_APPVERSION: '${{vars.APPLICATION_NAME}}:${{github.ref_name}}-remediate-${{github.run_id}}'
          AVIATOR_URL: ${{vars.AVIATOR_URL}}
          AVIATOR_APP: "${{vars.APPLICATION_NAME}}"
          AVIATOR_TOKEN: ${{secrets.AVIATOR_TOKEN}}
          DO_SETUP: true
          SETUP_EXTRA_OPTS: '--issue-template "Prioritized High Risk Issue Template"'
          DO_WAIT: true
          DO_JOB_SUMMARY: true
          DO_SAST_EXPORT: false

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v3
        with:
          fcli: ${{vars.FCLI_VERSION}}

      - name: SSC session login
        run: fcli ssc session login --url ${{vars.SSC_URL}} --token "${{secrets.SSC_TOKEN}}"

      - name: Apply remediations
        run: |
          ARTIFACT_ID=$(fcli ssc artifact ls --av "${{vars.APPLICATION_NAME}}:${{github.ref_name}}-remediate-${{github.run_id}}" --output json | 
            jq -r '
              [.[] | select(.originalFileName | startswith("aviator_"))] | 
              sort_by(.uploadDate) | 
              last | 
              .id
            ')
          echo "Latest aviator artifact ID: $ARTIFACT_ID"
          fcli aviator ssc apply-remediations --artifact-id $ARTIFACT_ID

      - name: Create Pull Request
        uses: fortify/3rdparty-actions/actions/peter-evans/create-pull-request/v8@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'auto-remediation by OpenText SAST Aviator'
          branch: aviator/scan-audit-remediate-${{github.run_id}}
          delete-branch: true
          title: 'Remediation of security issues detected by OpenText SAST'
          body: |
            Remediation of security issues detected by OpenText SAST.
            This PR was automatically created by OpenText SAST Aviator.
            Please review carefully before merging.
